@URL = http://localhost:8080/post

//get all
GET {{URL}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MSIsImlhdCI6MTczODUzNTA1Mn0.cd9aMmFgGPxH4HvB-GD7Y8a34VhZA1ceTHJXtiSoC-k
###
//get post
GET {{URL}}/6768d070d250b9230025598a HTTP/1.1
###
//get post by user
GET {{URL}}/user/6768771f709b3345cf9924bf HTTP/1.1
###
//add post
POST {{URL}} HTTP/1.1
Content-Type: application/json

{
    "type": "IMAGE",
    "key": "adf",
    "likes": 1,
    "description": "adf",
    "comments": ["asdf", "asdf"],
    "date": "2024-01-23",
    "userID": "asdf"
}
###
//update post
PUT {{URL}}/update HTTP/1.1
Content-Type: application/json

{
  "postID": "6768d070d250b9230025598a",
  "type": "IMAGE",
  "key": "asdasdfasdf",
  "likes": 1,
  "description": "asdfasdfasdfdas",
  "comments": [
    "asdf",
    "asdf",
    "asdf"
  ],
  "date": "2024-01-23T00:00:00.000+00:00",
  "userID": "asdfasdfasdfasdf"
}
###
//update likes
PUT {{URL}}/update/likes/679d82e0ec2a0f548b04ab9d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MSIsImlhdCI6MTczODQ0NTk4NH0.l6OI19RrOn-2SCUQlghRE_RS0LBc3FJnjyh_0p3Kp3g
Content-Type: application/json

{
  "postID": "679e902796ec9f6d4b7681e5",
  "likes": 1
}
###
//add comment
POST {{URL}}/addComment/679d82e0ec2a0f548b04ab9d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MSIsImlhdCI6MTczODQ2MzcxNX0.qCNkYNHor8e9iyiaaR8Edwp1OfO4E9DxsNI5fvv5Hvo
Content-Type: application/json

{
  "postID": "679ec7954d8b0b5cfaa9e3f7",
  "comments": {
    "679d82e0ec2a0f548b04ab9d": ["i am a comment"]
  }
}
###
//delete
DELETE {{URL}}/delete HTTP/1.1
Content-Type: application/json 

{
  "postID": "676ce3db1ece932efdea25af"
}
###
//delete by user
DELETE {{URL}}/deletebyuser/6768771f709b3345cf9924bf