@URL = http://localhost:8080
# @URL = http://184.72.160.8:80
# @URL = http://Insta-ko-app-env.eba-hivvfjqc.us-east-1.elasticbeanstalk.com:80

GET {{URL}}/get 
###
//register
POST {{URL}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "test3",
    "password": "pw3"
}
###
//login
POST {{URL}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "test1",
    "password": "test1"
}